name: Jekyll CI Pipeline

on:
  push:
    branches: [ deployment ]
#   pull_request:
#     branches: [ deployment ]

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
